package org.apache.spark.examples.ml

import org.apache.spark.sql.types.{DataTypes, StructField, StructType}

import scala.collection.mutable.ArrayBuffer

class createSchema {

  /**
    *
    * @return  定义数据框各个字段的类型、格式
    */
  def getSchema:StructType = {
    var fields: ArrayBuffer[StructField] = new ArrayBuffer[StructField]()
    fields += DataTypes.createStructField("click", DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("os",DataTypes.StringType,false)
    fields += DataTypes.createStructField("newuser",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("ifbrowsed",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_total",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_1",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_2",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_3",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_4",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_5",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_6",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("user_pv_7",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("featpref_1",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_2",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_3",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_4",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_5",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_6",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_7",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_8",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_9",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_10",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_11",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_12",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_13",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_14",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("featpref_15",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("sum_pv_1",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sum_pv_2",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sum_pv_3",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sum_pv_4",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sum_pv_5",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sum_pv_6",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sum_pv_7",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("poi_price",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poi_outdays",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("user_locprovince",DataTypes.StringType,false)
    fields += DataTypes.createStructField("user_locregion",DataTypes.StringType,false)
    fields += DataTypes.createStructField("user_loccountry",DataTypes.StringType,false)
    fields += DataTypes.createStructField("poi_locprovince",DataTypes.StringType,false)
    fields += DataTypes.createStructField("poi_locregion",DataTypes.StringType,false)
    fields += DataTypes.createStructField("poi_loccountry",DataTypes.StringType,false)
    fields += DataTypes.createStructField("samecity",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sameprovince",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("sameregion",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("samecountry",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("catepref_1",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("catepref_2",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("catepref_3",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("catepref_4",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("catepref_5",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("catepref_6",DataTypes.DoubleType,false)
    //    fields += DataTypes.createStructField("valumax_n",DataTypes.DoubleType,false)
    //    fields += DataTypes.createStructField("valumax_i",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("valumax_all",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("total_person_num",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("last_person_num",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("last_month_person_num",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("last_year_person_num",DataTypes.IntegerType,false)
    fields += DataTypes.createStructField("poi_level",DataTypes.StringType,false)
    fields += DataTypes.createStructField("idts",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_1",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_2",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_3",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_4",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_5",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_6",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_7",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_8",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_9",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_10",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("poipref_11",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("itf_poi_price",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("itf_bookcitypoi_price",DataTypes.DoubleType,false)
    fields += DataTypes.createStructField("itf_bookcitypoi_num",DataTypes.IntegerType,false)
    val schema:StructType = DataTypes.createStructType(fields.toArray)
    schema
  }

}
